spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 9722
      jdbc-url: jdbc:mysql://localhost:3306/testapi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    jpa:
      show-spl: true
      open-in-view: true
      properties:
        hibernate:
          default_batch_fetch_size: 100
          dialect: org.hibernate.dialect.MySQLDialect
          order_updates: true
          order_inserts: true
          generate_statistics: false
          format_sql: true
      hibernate:
          ddl-auto: update


