coverImage: "/Users/geumjiun/Downloads/"
logoImage: "/Users/geumjiun/Downloads/"
menuImage: "/Users/geumjiun/Downloads/"
questionImage: "/Users/geumjiun/Downloads/"

#이미지 저장 경로
server:
  port: 9033
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jwt:
    secret: gogofndgogosafe#!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/testapi?serverTimezone=Asia/Seoul
    username: root
    password: 9722
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs/json
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

