coverImage: "/users/june/eLearning/eLearningCoverImage/"
logoImage: "/users/june/eLearning/eLearningLogoImage/"
menuImage: "/users/june/eLearning/eLearningMenu/"
questionImage: "/users/june/eLearning/eLearningQuestionImage/"

#coverImage: "C:/eLearning/coverImage"
#logoImage: "C:/eLearning/logoImage"
#menuImage: "C:/eLearning/menuImage"
#questionImage: "C:/eLearning/eLeaning/questionImage"

#이미지 저장 경로
server:
  port: 9033
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jwt:
    secret: gogofndgogosafe#!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/testapi?serverTimezone=Asia/Seoul
    username: root
    password: 9722
#    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 30
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs/json
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

