
server:
  port: 9033
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jwt:
    secret: gogofndgogosafe#!
  datasource:
    url: jdbc:mysql://localhost:3306/testapi?serverTimezone=Asia/Seoul
    username: root
    password: 9722
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
